// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';
import {screen} from '../models';
import {permissions} from '../models';
import {workspace} from '../models';
import {updater} from '../models';
import {grokrunner} from '../models';
import {storage} from '../models';
import {skills} from '../models';
import {main} from '../models';

export function AppendSystemLog(arg1:logger.LogEntry):Promise<void>;

export function AutoDetectGrokBinaryPath():Promise<string>;

export function CancelSession(arg1:string):Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function CaptureScreenExcludingSelf(arg1:number):Promise<screen.SnapshotResult>;

export function CheckAllSystemPermissions():Promise<permissions.AllPermissionsStatus>;

export function CheckAndRequestAccessibilityPermissions():Promise<permissions.Status>;

export function CheckDirectoryExists(arg1:string):Promise<boolean>;

export function CheckFileExists(arg1:string,arg2:string):Promise<workspace.FileCheckResult>;

export function CheckForUpdates(arg1:string):Promise<updater.UpdateCheckResult>;

export function CheckGrokInstallation():Promise<grokrunner.GrokInstallStatus>;

export function CheckMicrophonePermission():Promise<permissions.Status>;

export function CheckMultipleFilesExists(arg1:string,arg2:Array<string>):Promise<Record<string, workspace.FileCheckResult>>;

export function CheckScreenCapturePermission():Promise<permissions.Status>;

export function CleanVoiceCache():Promise<void>;

export function CleanupSkillImportTemp(arg1:string):Promise<void>;

export function ClearPersistedLogs():Promise<void>;

export function ClearSnapshotCache():Promise<screen.ClearCacheResult>;

export function CloseSessionTerminals(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CommitWorkspaceChanges(arg1:string,arg2:string):Promise<void>;

export function CompactSession(arg1:string,arg2:string):Promise<grokrunner.SessionUsageStats>;

export function CreateTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteGrokSession(arg1:string,arg2:string):Promise<void>;

export function DeleteSessionTempFiles(arg1:Array<string>):Promise<void>;

export function DeleteVoiceAudioRecording(arg1:string):Promise<void>;

export function DiscoverGrokSessions(arg1:string):Promise<Array<grokrunner.GrokSessionMetadata>>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function EnsureTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteSkillSetupCommand(arg1:string,arg2:string):Promise<void>;

export function GetAppSettings():Promise<storage.AppSettings>;

export function GetAppVersion():Promise<string>;

export function GetAvailableModels():Promise<Array<grokrunner.ModelInfo>>;

export function GetChangelogHistory():Promise<Array<updater.ReleaseInfo>>;

export function GetGrokBinaryPath():Promise<string>;

export function GetInstalledSkills():Promise<Array<skills.Skill>>;

export function GetPlanContent(arg1:string):Promise<string>;

export function GetSessionUsage(arg1:string,arg2:string):Promise<grokrunner.SessionUsageStats>;

export function GetSnapshotCacheStats():Promise<screen.CacheStats>;

export function GetSystemAudioInputDevices():Promise<Array<permissions.AudioDeviceInfo>>;

export function GetTerminalBuffer(arg1:string):Promise<string>;

export function GetUIState():Promise<storage.UIState>;

export function GetWorkspaceFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetWorkspaceGitStatus(arg1:string):Promise<workspace.GitStatusResult>;

export function GetWorkspaces():Promise<Array<storage.Workspace>>;

export function Greet(arg1:string):Promise<string>;

export function InstallDiscoveredSkills(arg1:skills.SkillInstallPayload):Promise<skills.SkillInstallResult>;

export function InstallGrokCLI():Promise<grokrunner.GrokInstallStatus>;

export function InterruptTerminal(arg1:string):Promise<void>;

export function KillTerminal(arg1:string):Promise<void>;

export function LoadGrokSessionHistory(arg1:string,arg2:string):Promise<Array<grokrunner.DiscoveredChatMessage>>;

export function LoadPersistedLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function MuteSystemVolume():Promise<main.VolumeMuteResult>;

export function OpenAccessibilitySettings():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenMicrophoneSettings():Promise<void>;

export function OpenPathInSystem(arg1:string):Promise<void>;

export function OpenScreenCaptureSettings():Promise<void>;

export function PullWorkspaceChanges(arg1:string):Promise<string>;

export function PushWorkspaceChanges(arg1:string):Promise<string>;

export function ReadWorkspaceDirectory(arg1:string,arg2:string):Promise<Array<workspace.FileItem>>;

export function ReadWorkspaceFileContent(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RegisterGlobalDictationShortcut(arg1:string):Promise<void>;

export function RegisterGlobalSnapshotShortcut(arg1:string):Promise<void>;

export function RequestMicrophonePermission():Promise<permissions.Status>;

export function RequestScreenCapturePermission():Promise<permissions.Status>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondPermission(arg1:grokrunner.PermissionResponse):Promise<void>;

export function RestoreSystemVolume(arg1:number,arg2:boolean):Promise<void>;

export function RevealGrokConfigFile():Promise<void>;

export function RevertWorkspaceFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function RunPromptStream(arg1:grokrunner.PromptRequest):Promise<void>;

export function SaveAppSettings(arg1:storage.AppSettings):Promise<void>;

export function SaveLogExport(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveMarkdownExport(arg1:string,arg2:string):Promise<string>;

export function SaveTemporaryImage(arg1:string,arg2:string):Promise<screen.SnapshotResult>;

export function SaveUIState(arg1:storage.UIState):Promise<void>;

export function SaveVoiceAudioRecording(arg1:string,arg2:string):Promise<string>;

export function SaveWorkspaces(arg1:Array<storage.Workspace>):Promise<void>;

export function ScanGitHubSkills(arg1:string):Promise<skills.SkillAnalysisResult>;

export function SearchSkills(arg1:string,arg2:string):Promise<Array<skills.Skill>>;

export function SelectWorkspaceDirectory():Promise<string>;

export function SetGrokBinaryPath(arg1:string):Promise<void>;

export function TranscribeAudioWithGrok(arg1:string,arg2:string):Promise<string>;

export function UnregisterGlobalDictationShortcut():Promise<void>;

export function UnregisterGlobalSnapshotShortcut():Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
