// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendSystemLog(arg1) {
  return window['go']['main']['App']['AppendSystemLog'](arg1);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function CancelUpdateDownload() {
  return window['go']['main']['App']['CancelUpdateDownload']();
}

export function CaptureScreenExcludingSelf(arg1) {
  return window['go']['main']['App']['CaptureScreenExcludingSelf'](arg1);
}

export function CheckAndRequestAccessibilityPermissions() {
  return window['go']['main']['App']['CheckAndRequestAccessibilityPermissions']();
}

export function CheckDirectoryExists(arg1) {
  return window['go']['main']['App']['CheckDirectoryExists'](arg1);
}

export function CheckFileExists(arg1, arg2) {
  return window['go']['main']['App']['CheckFileExists'](arg1, arg2);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function CheckMicrophonePermission() {
  return window['go']['main']['App']['CheckMicrophonePermission']();
}

export function CheckMultipleFilesExists(arg1, arg2) {
  return window['go']['main']['App']['CheckMultipleFilesExists'](arg1, arg2);
}

export function CleanupSkillImportTemp(arg1) {
  return window['go']['main']['App']['CleanupSkillImportTemp'](arg1);
}

export function ClearPersistedLogs() {
  return window['go']['main']['App']['ClearPersistedLogs']();
}

export function ClearSnapshotCache() {
  return window['go']['main']['App']['ClearSnapshotCache']();
}

export function CloseSessionTerminals(arg1) {
  return window['go']['main']['App']['CloseSessionTerminals'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CommitWorkspaceChanges(arg1, arg2) {
  return window['go']['main']['App']['CommitWorkspaceChanges'](arg1, arg2);
}

export function CompactSession(arg1, arg2) {
  return window['go']['main']['App']['CompactSession'](arg1, arg2);
}

export function CreateTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4);
}

export function DeleteGrokSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteGrokSession'](arg1, arg2);
}

export function DeleteSessionTempFiles(arg1) {
  return window['go']['main']['App']['DeleteSessionTempFiles'](arg1);
}

export function DeleteVoiceAudioRecording(arg1) {
  return window['go']['main']['App']['DeleteVoiceAudioRecording'](arg1);
}

export function DiscoverGrokSessions(arg1) {
  return window['go']['main']['App']['DiscoverGrokSessions'](arg1);
}

export function DownloadAndInstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1, arg2);
}

export function ExecuteSkillSetupCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSkillSetupCommand'](arg1, arg2);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetChangelogHistory() {
  return window['go']['main']['App']['GetChangelogHistory']();
}

export function GetInstalledSkills() {
  return window['go']['main']['App']['GetInstalledSkills']();
}

export function GetPlanContent(arg1) {
  return window['go']['main']['App']['GetPlanContent'](arg1);
}

export function GetSessionUsage(arg1, arg2) {
  return window['go']['main']['App']['GetSessionUsage'](arg1, arg2);
}

export function GetSnapshotCacheStats() {
  return window['go']['main']['App']['GetSnapshotCacheStats']();
}

export function GetSystemAudioInputDevices() {
  return window['go']['main']['App']['GetSystemAudioInputDevices']();
}

export function GetTerminalBuffer(arg1) {
  return window['go']['main']['App']['GetTerminalBuffer'](arg1);
}

export function GetUIState() {
  return window['go']['main']['App']['GetUIState']();
}

export function GetWorkspaceFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetWorkspaceFileDiff'](arg1, arg2);
}

export function GetWorkspaceGitStatus(arg1) {
  return window['go']['main']['App']['GetWorkspaceGitStatus'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDiscoveredSkills(arg1) {
  return window['go']['main']['App']['InstallDiscoveredSkills'](arg1);
}

export function LoadGrokSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadGrokSessionHistory'](arg1, arg2);
}

export function LoadPersistedLogs(arg1) {
  return window['go']['main']['App']['LoadPersistedLogs'](arg1);
}

export function OpenAccessibilitySettings() {
  return window['go']['main']['App']['OpenAccessibilitySettings']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenMicrophoneSettings() {
  return window['go']['main']['App']['OpenMicrophoneSettings']();
}

export function OpenPathInSystem(arg1) {
  return window['go']['main']['App']['OpenPathInSystem'](arg1);
}

export function PullWorkspaceChanges(arg1) {
  return window['go']['main']['App']['PullWorkspaceChanges'](arg1);
}

export function PushWorkspaceChanges(arg1) {
  return window['go']['main']['App']['PushWorkspaceChanges'](arg1);
}

export function ReadWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceDirectory'](arg1, arg2);
}

export function ReadWorkspaceFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadWorkspaceFileContent'](arg1, arg2, arg3);
}

export function RegisterGlobalSnapshotShortcut(arg1) {
  return window['go']['main']['App']['RegisterGlobalSnapshotShortcut'](arg1);
}

export function RequestMicrophonePermission() {
  return window['go']['main']['App']['RequestMicrophonePermission']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespondPermission(arg1) {
  return window['go']['main']['App']['RespondPermission'](arg1);
}

export function RevealGrokConfigFile() {
  return window['go']['main']['App']['RevealGrokConfigFile']();
}

export function RevertWorkspaceFiles(arg1, arg2) {
  return window['go']['main']['App']['RevertWorkspaceFiles'](arg1, arg2);
}

export function RunPromptStream(arg1) {
  return window['go']['main']['App']['RunPromptStream'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveLogExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLogExport'](arg1, arg2, arg3);
}

export function SaveMarkdownExport(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownExport'](arg1, arg2);
}

export function SaveTemporaryImage(arg1, arg2) {
  return window['go']['main']['App']['SaveTemporaryImage'](arg1, arg2);
}

export function SaveUIState(arg1) {
  return window['go']['main']['App']['SaveUIState'](arg1);
}

export function SaveVoiceAudioRecording(arg1, arg2) {
  return window['go']['main']['App']['SaveVoiceAudioRecording'](arg1, arg2);
}

export function SaveWorkspaces(arg1) {
  return window['go']['main']['App']['SaveWorkspaces'](arg1);
}

export function ScanGitHubSkills(arg1) {
  return window['go']['main']['App']['ScanGitHubSkills'](arg1);
}

export function SearchSkills(arg1, arg2) {
  return window['go']['main']['App']['SearchSkills'](arg1, arg2);
}

export function SelectWorkspaceDirectory() {
  return window['go']['main']['App']['SelectWorkspaceDirectory']();
}

export function SetGrokBinaryPath(arg1) {
  return window['go']['main']['App']['SetGrokBinaryPath'](arg1);
}

export function TranscribeAudioWithGrok(arg1, arg2) {
  return window['go']['main']['App']['TranscribeAudioWithGrok'](arg1, arg2);
}

export function UnregisterGlobalSnapshotShortcut() {
  return window['go']['main']['App']['UnregisterGlobalSnapshotShortcut']();
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
