// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function CaptureScreenExcludingSelf(arg1) {
  return window['go']['main']['App']['CaptureScreenExcludingSelf'](arg1);
}

export function DeleteGrokSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteGrokSession'](arg1, arg2);
}

export function DiscoverGrokSessions(arg1) {
  return window['go']['main']['App']['DiscoverGrokSessions'](arg1);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetInstalledSkills() {
  return window['go']['main']['App']['GetInstalledSkills']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadGrokSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadGrokSessionHistory'](arg1, arg2);
}

export function RespondPermission(arg1) {
  return window['go']['main']['App']['RespondPermission'](arg1);
}

export function RunPromptStream(arg1) {
  return window['go']['main']['App']['RunPromptStream'](arg1);
}

export function SaveMarkdownExport(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownExport'](arg1, arg2);
}

export function SearchSkills(arg1, arg2) {
  return window['go']['main']['App']['SearchSkills'](arg1, arg2);
}

export function SelectWorkspaceDirectory() {
  return window['go']['main']['App']['SelectWorkspaceDirectory']();
}

export function SetGrokBinaryPath(arg1) {
  return window['go']['main']['App']['SetGrokBinaryPath'](arg1);
}
