// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screen} from '../models';
import {skills} from '../models';
import {grokrunner} from '../models';

export function CancelSession(arg1:string):Promise<void>;

export function CaptureScreenExcludingSelf(arg1:number):Promise<screen.SnapshotResult>;

export function GetInstalledSkills():Promise<Array<skills.Skill>>;

export function Greet(arg1:string):Promise<string>;

export function RespondPermission(arg1:grokrunner.PermissionResponse):Promise<void>;

export function RunPromptStream(arg1:grokrunner.PromptRequest):Promise<void>;

export function SearchSkills(arg1:string,arg2:string):Promise<Array<skills.Skill>>;

export function SetGrokBinaryPath(arg1:string):Promise<void>;
