// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screen} from '../models';
import {permissions} from '../models';
import {workspace} from '../models';
import {grokrunner} from '../models';
import {skills} from '../models';

export function CancelSession(arg1:string):Promise<void>;

export function CaptureScreenExcludingSelf(arg1:number):Promise<screen.SnapshotResult>;

export function CheckAndRequestAccessibilityPermissions():Promise<permissions.Status>;

export function CheckDirectoryExists(arg1:string):Promise<boolean>;

export function CheckFileExists(arg1:string,arg2:string):Promise<workspace.FileCheckResult>;

export function CheckMicrophonePermission():Promise<permissions.Status>;

export function CheckMultipleFilesExists(arg1:string,arg2:Array<string>):Promise<Record<string, workspace.FileCheckResult>>;

export function CleanupSkillImportTemp(arg1:string):Promise<void>;

export function ClearSnapshotCache():Promise<screen.ClearCacheResult>;

export function CommitWorkspaceChanges(arg1:string,arg2:string):Promise<void>;

export function CompactSession(arg1:string,arg2:string):Promise<grokrunner.SessionUsageStats>;

export function DeleteGrokSession(arg1:string,arg2:string):Promise<void>;

export function DeleteSessionTempFiles(arg1:Array<string>):Promise<void>;

export function DeleteVoiceAudioRecording(arg1:string):Promise<void>;

export function DiscoverGrokSessions(arg1:string):Promise<Array<grokrunner.GrokSessionMetadata>>;

export function ExecuteSkillSetupCommand(arg1:string,arg2:string):Promise<void>;

export function GetAvailableModels():Promise<Array<grokrunner.ModelInfo>>;

export function GetInstalledSkills():Promise<Array<skills.Skill>>;

export function GetSessionUsage(arg1:string,arg2:string):Promise<grokrunner.SessionUsageStats>;

export function GetSnapshotCacheStats():Promise<screen.CacheStats>;

export function GetWorkspaceFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetWorkspaceGitStatus(arg1:string):Promise<workspace.GitStatusResult>;

export function Greet(arg1:string):Promise<string>;

export function InstallDiscoveredSkills(arg1:skills.SkillInstallPayload):Promise<skills.SkillInstallResult>;

export function LoadGrokSessionHistory(arg1:string,arg2:string):Promise<Array<grokrunner.DiscoveredChatMessage>>;

export function OpenAccessibilitySettings():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenMicrophoneSettings():Promise<void>;

export function OpenPathInSystem(arg1:string):Promise<void>;

export function PullWorkspaceChanges(arg1:string):Promise<string>;

export function PushWorkspaceChanges(arg1:string):Promise<string>;

export function ReadWorkspaceDirectory(arg1:string,arg2:string):Promise<Array<workspace.FileItem>>;

export function ReadWorkspaceFileContent(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RegisterGlobalSnapshotShortcut(arg1:string):Promise<void>;

export function RequestMicrophonePermission():Promise<permissions.Status>;

export function RespondPermission(arg1:grokrunner.PermissionResponse):Promise<void>;

export function RevealGrokConfigFile():Promise<void>;

export function RevertWorkspaceFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function RunPromptStream(arg1:grokrunner.PromptRequest):Promise<void>;

export function SaveMarkdownExport(arg1:string,arg2:string):Promise<string>;

export function SaveTemporaryImage(arg1:string,arg2:string):Promise<screen.SnapshotResult>;

export function SaveVoiceAudioRecording(arg1:string,arg2:string):Promise<string>;

export function ScanGitHubSkills(arg1:string):Promise<skills.SkillAnalysisResult>;

export function SearchSkills(arg1:string,arg2:string):Promise<Array<skills.Skill>>;

export function SelectWorkspaceDirectory():Promise<string>;

export function SetGrokBinaryPath(arg1:string):Promise<void>;

export function TranscribeAudioWithGrok(arg1:string,arg2:string):Promise<string>;

export function UnregisterGlobalSnapshotShortcut():Promise<void>;
